### ISSUE TITLE
Missing / not found OpenAL libraries after lucia installation

### ISSUE THREAD

**Issue by NicklasMCHD** [luciasoftware/lucia#12]
When lucia has been installed and someone tries to use the OpenAL audio backend it complains about missing the required libraries (dylib, so, dlls).

I've seen this both when trying to setup travis-ci, ReadTheDocs and while running the tests after a fresh installation.
But the strange thing is, that we are setting the PYAL_DLL path, so it should work.

```
import os
import platform

os_bit, os_name = platform.architecture()
os.environ["PYAL_DLL_PATH"] = os.path.join(
	os.path.dirname(os.path.realpath(__file__)), "lib", os_bit
)
```

And the dlls are placed in the correct folder, so don't know what's really going on here.

**Comment by pauliyobo** [comment]
Is it possile to provide the traceback?

**Comment by NicklasMCHD** [comment]
This was the error we got from ag.net

```
Importing lucia
Initializing lucia
Traceback (most recent call last):
  File "C:\Users\Ashley\Downloads\lucia-master\examples\demo1\main.py", line 25, in <module>
    lucia.initialize(audiobackend=lucia.AudioBackend.OPENAL)
  File "C:\python\lib\site-packages\lucia\__init__.py", line 72, in initialize
    from .audio import openal as backend_openal
  File "C:\python\lib\site-packages\lucia\audio\openal\__init__.py", line 16, in <module>
    from openal import (
  File "C:\python\lib\site-packages\openal\__init__.py", line 1, in <module>
    from .al import *
  File "C:\python\lib\site-packages\openal\al.py", line 17, in <module>
    raise ExternalLibraryError("OpenAL library couldn't be found")
openal.library_loader.ExternalLibraryError: OpenAL library couldn't be found
```

**Comment by pauliyobo** [comment]
Hello. I was finally able to investigate.
Openal was complaining because because when it loads libraries it uses ctypes.util.find_library() which searches for libraries in the system environment path variable. What I just did was to extend the path environment variable with the path that points to the library directory.

**Comment by pauliyobo** [comment]
As it turned out the error the build was getting was not related to the traceback showed above.
I'm going to close this issue since I believe that on platforms that have all devices installed this error is not occurring any more. Should I be proved wrong the issue will be reopened.
