### ISSUE TITLE
Getting lucia's documentation on ReadTheDocs

### ISSUE THREAD

**Issue by NicklasMCHD** [luciasoftware/lucia#8]
I'm in the process of getting lucia's documentation on RTD but I've incountered some problems, some of which, I've been able to resolve myself.

# Problems and stauts

* Missing eSpeak binaries on Linux (fixed in lucia/out.py - Resolved).
* Missing OpenAL library files.
* Missing bson dependency in requirements.txt file.
* Getting errors about missing files sphinx needs.

### Traceback for OpenAL.

```
WARNING: autodoc: failed to import module 'openal.sound' from module 'lucia.audio'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/lucia/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/lucia/checkouts/latest/lucia/audio/openal/__init__.py", line 16, in <module>
    from openal import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/lucia/envs/latest/lib/python3.7/site-packages/openal/__init__.py", line 84, in <module>
    os.getenv("PYAL_DLL_PATH"))
  File "/home/docs/checkouts/readthedocs.org/user_builds/lucia/envs/latest/lib/python3.7/site-packages/openal/__init__.py", line 51, in __init__
    raise RuntimeError("could not find any library for %s" % libinfo)
RuntimeError: could not find any library for OpenAL
```

### Missing modules

```
WARNING: autodoc: failed to import module 'network' from module 'lucia.utils'; the following exception was raised:
No module named 'bson'
```

### Error from sphinx

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/lucia/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/lucia/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/lucia/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/lucia/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/lucia/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 472, in read
    self.env.doc2path(self.config.master_doc))
sphinx.errors.SphinxError: master file /home/docs/checkouts/readthedocs.org/user_builds/lucia/checkouts/latest/docs/contents.rst not found

Sphinx error:
master file /home/docs/checkouts/readthedocs.org/user_builds/lucia/checkouts/latest/docs/contents.rst not found
```

I've attached the full build log for rtd on this issue, but above should be all the information we would need to resolve this issue.

[9816173.txt](https://github.com/luciasoftware/lucia/files/3739065/9816173.txt)

**Comment by NicklasMCHD** [comment]
This issue has been fixed. We are instead of rtd, using github pages for the documentation.
The docs can be found at https://LuciaSoftware.github.io/lucia
